name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nodestone
      IMAGE_TAG: latest
      AWS_REGION: us-east-1
      ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY_ID }}.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}

    steps:
    - name: Check Out Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        submodules: 'true'

    - name: Update the package list
      run: sudo apt-get update
      
    - name: Install Podman
      run: |
        . /etc/os-release
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        wget -nv https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key -O- | sudo apt-key add -
        sudo apt-get update -qq
        sudo apt-get -qq -y install podman
        
    - name: Verify Podman installation
      run: podman --version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | podman login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

    - name: Build, Tag, and Push Image to Amazon ECR
      run: |
        podman build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
        podman push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Secure Deploy to Digital Ocean Droplet via SSH
      uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
        script: |
          echo "PORT=${{ secrets.PORT }}" > /home/${{ secrets.SERVER_USERNAME }}/scripts/${{ env.IMAGE_NAME }}.env
          cd /home/${{ secrets.SERVER_USERNAME }}/scripts
          ./deploy_container.sh ${{ env.IMAGE_NAME }}
